[package]
name = "kaitai"
version = "0.1.0"
authors = ["Oleg Dolgov <Oleg.Dolgov@gmail.com>", "Vitaly Reshetyuk <vitaly.askz.maknii@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
encoding-next = "0.3"
cp437 = "*"
unicode-segmentation = "1.9.0"
flate2 = "1.0"
once_cell = "1.15.0"
bytes = "1.3.0"